### PR TITLE
some build system improvements and fixes

### PR DESCRIPTION
**Pull request by nigoroll**

### CODE REVIEW

**Comment by nigoroll** [comment]
@lkarsten ping?

**Comment by nigoroll** [comment]
mostly dropping in favor of varnishcache/varnish-cache#2054, i'll review if some bits should go into the moved repo at https://github.com/varnishcache/libvmod-example

**Comment by nigoroll** [comment]
@Dridi actually I did push all of these commits now because the first 2 patches are independent of your work and the third may help to fix things until we get the merge of your m4 (which I hope to happen on Monday, but anyway...)

**Comment by dridi** [comment]
No problem

**Pull request closed without merging**
